FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-server \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config

RUN useradd -m -s /bin/bash sedme &&\
    echo "sedme:ncscofctfssh3" | chpasswd 

WORKDIR /home/sedme/

COPY challenge/ .

RUN chown sedme:sedme * && chmod 400 *

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
