FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-server \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd 

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/UsePAM no/UsePAM yes/' /etc/ssh/sshd_config

RUN useradd -m -s /bin/bash huntme &&\
    echo "huntme:ncscofctfssh1" | chpasswd 

WORKDIR /home/huntme/

COPY challenge/ .

RUN chown huntme:huntme * && chmod 400 *

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
