FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-server \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM no/UsePAM yes/' /etc/ssh/sshd_config

RUN useradd -m -s /bin/bash kitten &&\
    echo "kitten:ncscofctfssh0" | chpasswd 

WORKDIR /home/kitten/

COPY challenge/ .

RUN chown kitten:kitten * && chmod 400 *

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
